[package]
name = "fuzdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.lopdf]
version = "0.27.0"

[dependencies.tokio]
version = "1.20.0"
features = ["full"]

[dependencies.thirtyfour]
git = "https://github.com/kotatsuyaki/thirtyfour.git"
branch = "session-handle-elementqueryable"

[dependencies.anyhow]
version = "1.0"

[dependencies.indicatif]
version = "0.17.0-rc.11"

[dependencies.dialoguer]
version = "0.10.1"

[dependencies.console]
version = "0.15.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.futures]
version = "0.3"

[dependencies.thirtyfour-querier-derive]
version = "0.1.1"
